version: "3.6"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    image: camptocamp/mapfish_print:latest
    restart: always
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps
      - ./logs:/usr/local/tomcat/logs
networks:
    default:
        name: ${NETWORK_NAME}
        external: true

