version: "3.6"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    image: pkorduan/kvwmap-server:2.2.12
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    restart: "always"
    environment:
      # Environment variables with only a key are resolved to their values on the ma>
      - OS_USER=gisadmin
      - IP_EXTERN=$IP_EXTERN
      - DOMAIN_EXTERN=$DOMAIN_EXTERN
      - KVWMAP_INIT_PASSWORD=$KVWMAP_INIT_PASSWORD
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TERM=linux
      - COLUMNS=180
      - LINES=200
    volumes:
      - ${USER_DIR}/networks/${NETWORK_NAME}/volumes/proj/epsg:/usr/share/proj/epsg
      - ${USER_DIR}/networks/${NETWORK_NAME}/volumes/proj/MVTR2010.gsb:/usr/share/proj/MVTR2010.gsb
      - ${USER_DIR}/networks/${NETWORK_NAME}/volumes/proj/MVTRS4283.gsb:/usr/share/proj/MVTRS4283.gsb
      - ./apache2/sites-available:/etc/apache2/sites-available
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./apache2/conf-available:/etc/apache2/conf-available
      - ./cron/load_cron_files:/etc/cron.hourly/load_cron_files
      - ./php/7.4:/etc/php/7.4
      - ./www:/var/www
      - ./logs:/var/www/logs/apache2
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/pgsql/config/.pgpass:/root/.pgpass
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/pgsql/config/.pgpass_gisadmin:/home/gisadmin/.pgpass
networks:
    default:
        name: ${NETWORK_NAME}
        external: true
