version: "3.6"
networks:
  kvwmap_prod:
    name: ${NETWORK_NAME}
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    image: pkorduan/kvwmap-server:2.2.4
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    networks:
      ${NETWORK_NAME}:
        aliases:
          - ${SERVICE_NAME}
    environment:
      # Environment variables with only a key are resolved to their values on the ma>
      - OS_USER=gisadmin
      - IP_EXTERN=$IP_EXTERN
      - DOMAIN_EXTERN=$DOMAIN_EXTERN
      - KVWMAP_INIT_PASSWORD=$KVWMAP_INIT_PASSWORD
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TERM=linux
      - COLUMNS=180
      - LINES=200
    volumes:
      - ${USER_DIR}/networks/${NETWORK_NAME}/volumes/proj:/usr/share/proj/
      - ./apache2/sites-available:/etc/apache2/sites-available
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./cron/load_cron_files:/etc/cron.hourly/load_cron_files
      - ./php/7.3:/etc/php/7.3
      - ./www:/var/www
      - ./logs:/var/www/logs/apache2
