version: "3.6"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    image: pkorduan/kvwmap-server:2.2.4
    networks:
      ${NETWORK_NAME}:
        aliases:
          - ${SERVICE_NAME}
    environment:
      # Environment variables with only a key are resolved to their values on the ma>
      - OS_USER=gisadmin
      - IP_EXTERN=$IP_EXTERN
      - DOMAIN_EXTERN=$DOMAIN_EXTERN
      - KVWMAP_INIT_PASSWORD=$KVWMAP_INIT_PASSWORD
      - TERM=linux
      - COLUMNS=180
      - LINES=200
    volumes:
      - vol_pgpass:/root/.pgpass
      - vol_proj:/ust/share/proj/
      - ${USER_DIR}/networks/${NETWORK_NAME}/${SERVICE_NAME}/apache2/sites-available:/etc/apache2/sites-available
      - ${USER_DIR}/networks/${NETWORK_NAME}/${SERVICE_NAME}/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ${USER_DIR}/networks/${NETWORK_NAME}/${SERVICE_NAME}/cron/load_cron_files:/etc/cron.hourl/load_cron_files
      - ${USER_DIR}/networks/${NETWORK_NAME}/${SERVICE_NAME}/php/7.3:/etc/php/7.3
      - ${USER_DIR}/networks/${NETWORK_NAME}/${SERVICE_NAME}/phpmyadmin/config.inc.php:/srv/www/phpmyadmin/config.inc.php
      - ${USER_DIR}/networks/${NETWORK_NAME}/${SERVICE_NAME}/www:/var/www
