version: "3.8"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    image: dokuwiki/dokuwiki:stable
    restart: always
    environment:
      - SCRIPT_NAME=/dokuwiki
      - VIRTUAL_PATH=/dokuwiki
      - VIRTUAL_HOST=$DOMAIN
      - VIRTUAL_PORT=8080
    volumes:
      #- "./html:/var/www/html"
      #- "./storage:/storage"
      - "./apache2/sites-availabe:/etc/apache2/sites-available"
      - "./apache2/sites-enabled:/etc/apache2/sites-enabled"
      #- "./dokuwiki/data:/storage/data"
      #- "./dokuwiki/bin:/var/www/html/bin"
      #- "./dokuwiki/conf:/storage/conf"
    networks:
      - kvwmap_prod
      - proxy

networks:
  ${NETWORK_NAME}:
      external: true
  proxy:
    external: true
