version: '3'
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    image: nginx:stable
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    networks:
      - ${NETWORK_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www
      - ./log:/var/log/nginx

# When it not work with
# docker-compose run certbot
# run
# docker run -it --rm --name certbot \
#            -v "/home/gisadmin/proxy/www:/var/www" \
#            -v "/home/gisadmin/proxy/letsencrypt:/etc/letsencrypt" \
#            -v "/home/gisadmin/proxy/log:/var/log/letsencrypt" \
#            certbot/certbot certonly

networks:
    ${NETWORK_NAME}:
        external: true
