version: "3.8"

services:
  ${SERVICE_NAME}: 
    image: nginxproxy/nginx-proxy:latest
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    restart: always
    labels:
      - "com.github.nginx-proxy.nginx=true"
      - "com.github.nginx-proxy.docker-gen=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./www/html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    depends_on:
      - ${SERVICE_NAME}
    environment:
      - DEFAULT_EMAIL=peter.korduan@gdi-service.de
      - NGINX_PROXY_CONTAINER=${NETWORK_NAME}_${SERVICE_NAME}
      - NGINX_DOCKER_GEN_CONTAINER=${NETWORK_NAME}_${SERVICE_NAME}
    volumes:
      - ./acme:/etc/acme.sh
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./www/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    default:
        name: proxy
        external: true

