#!/bin/bash
# ToDos replace servername in nginx configs and
# fix error in phpmyadmin nginx conf.

install_service() {
	echo "Installation von Service proxy in Netzwerk 'proxy'"
	SERVICE_NAME=proxy
	echo "Service-Name: ${SERVICE_NAME}"

	NETWORK_NAME=proxy
	SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

	dcm create network proxy

	if [ -d "$SERVICE_PATH" ]; then
		echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
		return 1
	fi

	mkdir -p ${SERVICE_PATH}
	if $DEBUG ; then
		cp -vr ${USER_DIR}/kvwmap-server/service-templates/proxy/directory_template/* ${SERVICE_PATH}
	else
		cp -r ${USER_DIR}/kvwmap-server/service-templates/proxy/directory_template/* ${SERVICE_PATH}
	fi
	echo "Kopiere compose-template.yml nach ${SERVICE_PATH}"
	cp -v ${USER_DIR}/kvwmap-server/service-templates/proxy/compose-template.yml ${SERVICE_PATH}/
	cp -v ${USER_DIR}/kvwmap-server/service-templates/proxy/init-letsencrypt.sh ${SERVICE_PATH}/

	chown -R www-data.gisadmin ${SERVICE_PATH}
	chmod -R g+w ${SERVICE_PATH}
	chown root.root ${SERVICE_PATH}/init-letsencrypt.sh
	chmod 700 ${SERVICE_PATH}/init-letsencrypt.sh

#	dcm up proxy proxy

	echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet. Starten sie den Service mit dcm proxy up"
}
