version: "3.6"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    image: phpmyadmin:5.1.1-apache
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=$PMA_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - TERM=xterm
      - COLUMNS=180
      - LINES=200
    volumes:
      - ./etc/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./logs:/var/logs/apache2
networks:
    default:
        name: ${NETWORK_NAME}
        external: true
