#!/bin/bash

install_service() {
	echo "Installation von Service phpmyadmin in Netzwerk '${NETWORK_NAME}'"
	SERVICE_NAME=phpmyadmin
	echo "Service-Name=${SERVICE_NAME}"

	if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
		echo ""
		read -p "mysql Root Passwort: " -s MYSQL_ROOT_PASSWORD
		echo ""
		echo "MYSQL_ROOT_PASSWORD=\"${MYSQL_ROOT_PASSWORD}\"" >> ${USER_DIR}/networks/env
	fi

	if [ -z "$MYSQL_USER" ]; then
		echo ""
		read -p "Username mit dem phpMyAdmin auf die Datenbank zugreifen soll: " MYSQL_USER
		echo ""
		echo "MYSQL_USER=${MYSQL_USER}" >> ${USER_DIR}/networks/env
	fi

	if [ -z "$MYSQL_PASSWORD" ]; then
		echo ""
		read -p "mysql User Passwort: " -s MYSQL_PASSWORD
		echo ""
		echo "MYSQL_PASSWORD=\"${MYSQL_PASSWORD}\"" >> ${USER_DIR}/networks/${NETWORK_NAME}/env
	fi

	SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

	if [ -d "$SERVICE_PATH" ]; then
		echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
		return 1
	fi

	mkdir ${SERVICE_PATH}
	cp -r ${USER_DIR}/kvwmap-server/service-templates/phpmyadmin/directory_template/* ${SERVICE_PATH}
	cp    ${USER_DIR}/kvwmap-server/service-templates/phpmyadmin/compose-template.yml ${SERVICE_PATH}/

	chown -R 999.gisadmin ${SERVICE_PATH}/

	echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."

	sed -i '/user defined settings for phpmyadmin/a \  $cfg["Servers"][1]["host"] = "mysql";\n  $cfg["MaxNavigationItems"] = 75;' ${USER_DIR}/networks/${NETWORK_NAME}/services/phpmyadmin/etc/config.user.inc.php
}
