#!/bin/bash
# Initialize kvwmap-server
OS_USER=gisadmin
USER_DIR=/home/${OS_USER}
CURRENT_DIR=$(pwd)

# run this scirpt:
# wget -O inithost.sh https://raw.githubusercontent.com/pkorduan/kvwmap-server/master/inithost && chmod a+x inithost.sh && ./inithost.sh

# Install utils, lshw and git
apt-get update && apt-get install -y \
  apt-utils \
  lshw \
  git

if [ $(getent group ${OS_USER}) ] ; then
  echo "Group ${OS_USER} already exists."
else
  echo "Create group ${OS_USER} with id 1700."
  groupadd -g 1700 ${OS_USER}
fi

if [ $(getent passwd ${OS_USER}) ] ; then
  echo "User ${OS_USER} already exists."
else
  echo "Create user ${OS_USER} with id:17000 and add to group ${OS_USER} gid:1700."
  read -s -p "Enter password for OS user ${OS_USER}: " GISADMIN_PASSWORD
  useradd -u 17000 -g 1700 -d ${USER_DIR} -m -s /bin/bash -p $(echo ${GISADMIN_PASSWORD} | openssl passwd -1 -stdin) ${OS_USER}
fi
cd ${USER_DIR}

if [ -d ./kvwmap-server ] ; then
  echo 'Stop kvwmap-server and uninstall all.'
  dcm uninstall all
fi

if [ -d ./kvwmap-server ] ; then
  echo "Abort by user."
  exit
fi

echo 'Clone kvwmap-server repository to ./kvwmap-server.'
git clone https://github.com/pkorduan/kvwmap-server.git

source ~/.bashrc

read -p "Enter port for ssh login: " SSH_PORT
sed -i \
    -e "s|#PermitRootLogin prohibit-password|PermitRootLogin no|g" \
    -e "s|#Port 22|Port ${SSH_PORT}|g" \
    /etc/ssh/sshd_config
/etc/init.d/ssh reload

source ~/.bashrc

PATH=$PATH:/home/gisadmin/kvwmap-server

kvwmap-server/dcm install kvwmap

cd $CURRENT_DIR
read -p "Initscript löschen? (j/n) " answer
case ${answer:0:1} in
  j|J|y|Y )
    rm inithost.sh
  ;;
  * )
    echo "OK, nix passiert!"
  ;;
esac

echo "
Nächste Schritte zum installieren von kvwmap:"
echo "    $ dcm run all"
echo "    Browser öffnen mit der Adresse: https://${IP_EXTERN}/kvwmap/install.php"
echo ""
echo "Die Installation ist erfolgreich abgeschlossen."
echo "Achtung Der Zugang als root ist jetzt von außen gesperrt!"
echo "Sie können sich nur noch als gisadmin per ssh mit diesem Server verbinden."