version: "3"
services:
  web1:
    image: pkorduan/kvwmap-server:2.2.2
    container_name: "web1"
    restart: always
    environment:
    - OS_USER=
    - IP_EXTERN=
    - DOMAIN_EXTERN=
    - POSTGRES_ROOT_PASSWORD=
    - http_proxy=
    - no_proxy=
    - TERM=linux
    - COLUMNS=80
    - LINES=200
    - MYSQL_HOSTS_ALLOWED
    volumes:
    - $WWW_ROOT:/var/www
    - $USER_DIR/etc/postgresql/.pgpass:/root/.pgpass
    - $USER_DIR/etc/apache2/sites-available:/etc/apache2/sites-available
    - $USER_DIR/etc/apache2/sites-enabled:/etc/apache2/sites-enabled
    - $USER_DIR/etc/apache2/ssl:/etc/apache2/ssl
    - $USER_DIR/etc/apache2/letsencrypt:/etc/letsencrypt
    - $USER_DIR/etc/web/kvwmap_hourly:/etc/cron.hourly/load_gisadmin_cron_file
    - $USER_DIR/etc/web/kvwmap_monthly:/etc/cron.monthly/renew-certbot-auto
    - $USER_DIR/etc/php/7.3:/etc/php/7.3
    - $USER_DIR/etc/phpmyadmin/config.inc.php:/srv/www/phpmyadmin/config.inc.php
    - $USER_DIR/etc/proj/epsg:/usr/share/proj/epsg
    - $USER_DIR/etc/proj/MVTR2010.gsb:/usr/share/proj/MVTR2010.gsb
    - $USER_DIR/etc/proj/MVTRS4283.gsb:/usr/share/proj/MVTRS4283.gsb
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      kvwmap-dev:
        aliases:
          - web
    ports:
    - 80:80
    - 443:443
networks:
    kvwmap-dev:
        external: true
