#!/bin/bash

install_service() {

	echo "Installation von Service owncloud Version 10 in Netzwerk '${NETWORK_NAME}'"
	echo "optional neuer Service-Name (Default 'owncloud'): "
	read SERVICE_NAME

	if [ -z "$SERVICE_NAME" ]; then
		SERVICE_NAME=owncloud
	fi

	echo "Service-Name: ${SERVICE_NAME}"

	SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

	if [ -d "$SERVICE_PATH" ]; then
		echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
		return 1
	fi

	mkdir ${SERVICE_PATH}
	cp    ${USER_DIR}/kvwmap-server/service-templates/owncloud_10/compose-template.yml ${SERVICE_PATH}/

	echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."
}
