#!/bin/bash
#
# This script set the host ip of the postgresql docker container into the connection setting of the layers in kvwmap's mysql database.
# It replaces the former ip with the new ip of the pgsql container and set the new ip in the log file pgsql_container.ip
#
PGSQL_IP_FILE="/var/www/logs/pgsql_container.ip"

if [ ! -e $PGSQL_IP_FILE ] ; then
  echo "localhost" > $PGSQL_IP_FILE
fi

mysql --host=$MYSQL_PORT_3306_TCP_ADDR --port=$MYSQL_PORT_3306_TCP_PORT --user=root --password=$MYSQL_ENV_MYSQL_ROOT_PASSWORD --database="kvwmapdb" \
-e "UPDATE layer SET connection = REPLACE(connection, 'host=$(<$PGSQL_IP_FILE)', 'host=${PGSQL_PORT_5432_TCP_ADDR}');"

echo "$PGSQL_PORT_5432_TCP_ADDR" > $PGSQL_IP_FILE
