#!/bin/bash
#echo "Load variables in dcm nagios"
CARGOS+=("nagios")

usage_nagios() {
  echo "install nagios  Installiert das nagios Image."
  echo "run nagios      Erzeugt und startet nur den Container nagios."
  echo "rerun nagios    Stoppt, Entfernt und Erzeugt und Startet einen neuen nagios-Container."
  echo "start nagios    Startet nur den Container nagios."
  echo "status nagios   Zeigt den aktuellen Status des Container nagios an."
  echo "stop nagios     Startet nur den Container nagios."
  echo "uninsall nagios Deinstalliert das nagios image und die dazugehörigen lokalen Ressourcen auf dem Hostrechner."
}

install_nagios() {
  echo "Installiere nagios ..."

  source $USER_DIR/etc/nagios/env_and_volumes

  echo "
Erzeuge nagios Konfigurations-Verzeichnise: ${NAGIOS_CONFIG_DIR}"
  mkdir -p ${NAGIOS_CONFIG_DIR}/custom-plugin
  mkdir -p ${NAGIOS_CONFIG_DIR}/etc
  mkdir -p ${NAGIOS_CONFIG_DIR}/graph-etc
  mkdir -p ${NAGIOS_CONFIG_DIR}/graph-var
  mkdir -p ${NAGIOS_CONFIG_DIR}/var

  echo "
  Ziehe Image ${NAGIOS_IMAGE}:${NAGIOS_IMAGE_VERSION} von dockerhub"
  docker pull ${NAGIOS_IMAGE}:${NAGIOS_IMAGE_VERSION}

  echo "Der nagios container kann nun gestartet werden mit dem Befehl:"
  echo "dcm run nagios"
  echo "Anschließend den web container neu starten mit dem Befehl:"
  echo "dcm rerun web"
  echo "Dann kann auf die nagios GUI mit folgender URL zugegriffen werden:"
  echo "http://meineserverip:8080/"
  echo "Die initialen Zugangsdaten zur Admin GUI von nagios sind User: nagiosadmin und Password: nagios"
  echo "Um nagios Plugins nutzen zu können den Pfad /opt/Custom-Nagios-Plugins/ in der Konfiguration von nagios eintragen"
}

remove_nagios_container() {
  stop_nagios_container

  if [ "$(docker ps -a -q -f name=nagios -f status=exited)" ] ; then
    echo "Lösche Container ..."
    docker rm nagios
  else
    echo "Container nagios kann nicht gelöscht werden, weil er nicht existiert."
  fi
}

remove_nagios_image() {
  source $USER_DIR/etc/nagios/env_and_volumes
  echo "Lösche nagios Image: ${NAGIOS_IMAGE}:${NAGIOS_IMAGE_VERSION}"
  docker rmi ${NAGIOS_IMAGE}:${NAGIOS_IMAGE_VERSION}
}

run_nagios_container() {
  source $USER_DIR/etc/nagios/env_and_volumes
  echo "Erzeuge und starte den nagios Container"
  echo "mit volumes: ${nagios_volumes}"
  docker run --name ${NAGIOS_CONTAINER_NAME} \
    -h ${SERVER_NAME}-${NAGIOS_CONTAINER_NAME}-container \
    $nagios_volumes \
    $nagios_env_vars \
    $nagios_ports \
    --restart=always \
    -d ${NAGIOS_IMAGE}:${NAGIOS_IMAGE_VERSION}
}

set_nagios_web_link() {
  echo "Setzte nagios link zum Starten des web containers: --link nagios:nagios"
  CARGO_WEB_LINKS=${CARGO_WEB_LINKS}" --link nagios:nagios"
}

show_status() {
  echo "Status of container $NAGIOS_COINTAINER_NAME"
}

start_nagios_container() {
  echo "Starte nagios Container. Bitte warten ..."
  docker start nagios
}

stop_nagios_container() {
  if [ "$(docker ps -a -q -f name=nagios -f status=running)" ] ; then
    echo "Stoppe Container. Bitte warten ..."
    docker stop nagios
  else
    echo "Container nagios kann nicht gestoppt werden, weil er nicht läuft."
  fi
}

uninstall_nagios() {
  source $USER_DIR/etc/nagios/env_and_volumes
  remove_nagios_container
  
  echo "Dieser Befehl deinstalliert das image $NAGIOS_IMAGE:$NAGIOS_IMAGE_VERSION und auf Nachfrage alle dazugehörigen auf diesem Host gespeicherten Daten, die nagios genutzt hat."
  read -p "Wollen Sie das Image wirklich deinstallieren? (j/n)? " answer
  case ${answer:0:1} in
    j|J )
      docker rmi ${NAGIOS_IMAGE}:${NAGIOS_IMAGE_VERSION}
      echo "Lösche nagios Konfigurationsverzeichnis $USER_DIR/etc/nagios"
      ls -l $USER_DIR/etc/nagios
      rm -RI $USER_DIR/etc/nagios
      
      echo "So jetzt ist nagios weg."
      echo "Zum neu installieren nach ${USER_DIR} wechseln und folgenden Befehle eingeben:"
      echo "$ dcm install nagios"
      echo "$ dcm remove web"
      echo "$ dcm run nagios"
      echo "$ dcm run web"
      echo "Die Anwendung ist im Browser zu erreichen unter:"
      echo "http://meineserverip:8080/"
      echo "Die initialen Zugangsdaten zur Admin GUI von nagios sind User: admin und Password: nagios"
    ;;
    * )
      echo "OK, nix passiert!"
    ;;
  esac
}

cases_nagios() {
  case_found=true
  case "$1" in
    console)
      case $2 in
        nagios)
          echo "Öffne ein Terminal im Container in dem der nagios läuft ..."
          docker exec -it nagios /bin/bash
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    install)
      case $2 in
        nagios)
          install_nagios
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    ip)
      case $2 in
        nagios)
          show_container_ip $2
        ;;
        * )
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    uninstall)
      debug "Case uninstall in nagios"
      case $2 in
        nagios)
          #echo "Case nagios"
          uninstall_nagios
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    remove)
      debug "Case remove in nagios"
      case $2 in
        nagios)
          remove_nagios_container
          # Derzeit muss auch das dazugehörige Image gelöscht werden, weil sich nagios container
          # merkwürdigerweise nach dem ziehen eines Images immer nur einmal korrekt starten lassen.
          remove_nagios_image
        ;;
        * )
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    rerun)
      debug "Case rerun in nagios"
      case $2 in
        nagios)
          remove_nagios_container
          run_nagios_container
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    run)
      debug "Case run in nagios"
      case $2 in
        nagios)
          run_nagios_container
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    start)
      debug "Case start in nagios"
      case $2 in
        nagios)
          start_nagios_container
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    status)
      case $2 in
        nagios)
          show_container_status "nagios"
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    stop)
      debug "Case stop in nagios"
      case $2 in
        nagios)
          stop_nagios_container
        ;;
        *)
          debug "No subcase $2 in nagios"
          case_found=false
        ;;
      esac
    ;;

    *)
      #echo "No case found in dcm nagios"
      case_found=false
    ;;
  esac
  debug "Case found after cases nagios: $case_found"
}
