#!/bin/bash
CRONTAB_FILE="/var/www/cron/crontab_gisadmin"
if [ -s $CRONTAB_FILE ] ; then
  crontab -u gisadmin $CRONTAB_FILE
  echo "`date` Update gisadmins crontab." >> /var/www/logs/cron/cron.log
fi
