version: "3.6"
services:
  #pgsql:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    image: pkorduan/postgis:15-3.3
#    ports:
#      - "5432-5500:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGSQL_DB=postgres
      - PGSQL_USER=postgres
      - PGPASSFILE=/var/lib/postgresql/config/.pgpass
      - PGSQL_MAJOR_VERSION=15
      - POSTGIS_VERSION=3.3
    volumes:
      - ./config:/var/lib/postgresql/config:ro
      - ./data:/var/lib/postgresql/data
      - ./backup:/pgbackrest:ro
      - ./logs:/var/log/pgsql
      - ../../volumes/proj/proj.db:/usr/share/proj/proj.db
      - ../../volumes/proj/epsg:/usr/share/proj/epsg
      - ../../volumes/proj/MVTR2010.gsb:/usr/share/proj/MVTR2010.gsb
      - ../../volumes/proj/MVTRS4283.gsb:/usr/share/proj/MVTRS4283.gsb
#      - ./www:/var/www #optional
networks:
    ${NETWORK_NAME}:
        external: true
