#!/bin/bash

function install_service() {
	#$SERVICE_NAME und $NETWORK_NAME können verwendet werden
	if [ ! -d "$USER_DIR/networks/proxy/services/$PROXY_SERVICE" ]; then
		echo "Der Proxy fehlt! Wird installiert."
		dcm proxy create
	fi
	dcm create network ${NETWORK_NAME}

	echo "Zur Einrichtung des MySQL und phpMyAdmin Containers müssen Passwörter vergeben werden!"
	if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
		read -p "mysql Root Passwort: " -s MYSQL_ROOT_PASSWORD
		echo "MYSQL_ROOT_PASSWORD=\"${MYSQL_ROOT_PASSWORD}\"" >> ${USER_DIR}/networks/${NETWORK_NAME}/env
	fi

	if [ -z "$MYSQL_USER" ]; then
		#read -p "mysql User Name: " MYSQL_USER
		MYSQL_USER="kvwmap"
		echo "MYSQL_USER=\"${MYSQL_USER}\"" >> ${USER_DIR}/networks/${NETWORK_NAME}/env
	fi

	if [ -z "$MYSQL_PASSWORD" ]; then
		echo ""
		read -p "Passwort für mysql User ${MYSQL_USER}: " -s MYSQL_PASSWORD
		echo "MYSQL_PASSWORD=\"${MYSQL_PASSWORD}\"" >> ${USER_DIR}/networks/${NETWORK_NAME}/env
	fi

	dcm create service web ${NETWORK_NAME}
	dcm create service mariadb ${NETWORK_NAME}
	dcm create service phpmyadmin ${NETWORK_NAME}
	dcm create service pgsql ${NETWORK_NAME}
	dcm create service gdal ${NETWORK_NAME}

	SERVICE_NAME="kvwmap-server"
}
