#!/bin/bash

CRONTAB_USER=gisadmin
CRONTAB_FILE="/var/www/cron/$CRONTAB_USER"
if [ -s "$CRONTAB_FILE" ] ; then
  crontab -u "$CRONTAB_USER" "$CRONTAB_FILE"
  echo "$(date) Update gisadmins crontab." >> /var/www/logs/cron/cron.log
fi

CRONTAB_USER=root
KVWMAP=fis
CRONTAB_FILE="/var/www/cron/$CRONTAB_USER"
if [ -s "$CRONTAB_FILE" ] ; then
  crontab -u "$CRONTAB_USER" "$CRONTAB_FILE"
  echo "$(date) Update roots crontab." >> /var/www/logs/cron/cron.log
fi
