#!/bin/bash

#settings
DEBUG=false
OS_USER="gisadmin"
OS_USER_EXISTS=true
getent passwd $OS_USER >/dev/null 2>&1 && OS_USER_EXISTS=true
USER_DIR=/home/$OS_USER
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

export SERVER_NAME=$(hostname)
echo "Folgenden Hostname ermittelt: $SERVER_NAME"
export DOMAIN_NAME=$(hostname)
echo "Folgenden Domainname ermittelt: $DOMAIN_NAME"
export IP_EXTERN=$(hostname -I | awk '{print $1}')
echo "Folgende IP ermittelt: $IP_EXTERN"
TEMPLATEPATH="$SCRIPTPATH/service-templates"

KVWMAP_SERVER_VERSION=2.3.0
PROD_APP="kvwmap"
