#!/bin/bash

install_service() {
	echo "Installation von Service gdal in Netzwerk '${NETWORK_NAME}'"
	SERVICE_NAME=gdal
	echo "Service-Name=${SERVICE_NAME}"

	SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

	if [ -d "$SERVICE_PATH" ]; then
		echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
		return 1
	fi

	mkdir -p ${SERVICE_PATH}
	cp    ${USER_DIR}/kvwmap-server/service-templates/gdal/compose-template.yml ${SERVICE_PATH}/
    cp -r ${USER_DIR}/kvwmap-server/service-templates/gdal/directory_template/* ${SERVICE_PATH}/

    ln -rs ${USER_DIR}/networks/kvwmap_prod/services/postgres-16-3.5/config/.pgpass ${USER_DIR}/networks/kvwmap_prod/services/gdal/.pgpass
    ln -rs ${USER_DIR}/networks/kvwmap_prod/services/postgres-16-3.5/config/.pgpass_gisadmin ${USER_DIR}/networks/kvwmap_prod/services/gdal/.pgpass_gisadmin
    ln -rs ${USER_DIR}/networks/kvwmap_prod/services/web/www ${USER_DIR}/networks/kvwmap_prod/services/gdal/www

	echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."
}
