#!/bin/bash
######################################################################################################################
# script has to be called by root user to add backup-specific cronjobs                                               #
#####################################################################################################################
# path where backup-configs are written by php
RPC_SICHERUNGEN_CONFIG=/home/gisadmin/www/sicherungen

while read file
do
	chown root.root "$file"
	mv -f "$file" /etc/cron.d/
done < <(find "$RPC_SICHERUNGEN_CONFIG"/kvwmap_backup_crontab_* -type f)
exit 0
