#!/bin/bash

install_service() {

	echo "Installation von Service geonetwork in Netzwerk '${NETWORK_NAME}'"
#	echo "optional neuer Service-Name (Default 'geonetwork'): "
#	read SERVICE_NAME

	if [ -z "$SERVICE_NAME" ]; then
		SERVICE_NAME=geonetwork
	fi

	echo "Service-Name: ${SERVICE_NAME}"

	SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

	if [ -d "$SERVICE_PATH" ]; then
		echo "Der Service existiert in dem Netzwerk bereits. Starten Sie dieses Skript erneut und wählen Sie einen anderen Namen!"
		echo "${SERVICE_PATH} ist bereits vorhanden!"
		return 1
	fi

	mkdir ${SERVICE_PATH}
	cp    ${USER_DIR}/kvwmap-server/service-templates/geonetwork/compose-template.yml ${SERVICE_PATH}/
    cp    ${USER_DIR}/kvwmap-server/service-templates/geonetwork/init-letsencrypt.sh ${SERVICE_PATH}/
    mkdir ${SERVICE_PATH}/data
#	mkdir ${SERVICE_PATH}/db
    chgrp -R gisadmin ${SERVICE_PATH}/* 
    chmod -R g+w ${SERVICE_PATH}/*


    MIS_DOMAIN_CONF="$(cat ${USER_DIR}/networks/proxy/services/proxy/nginx/sites-available/default.conf | grep server_name | cut -d ';' -f 1 | awk '{print $2}')"
    cp ${USER_DIR}/kvwmap-server/service-templates/geonetwork/directory_template/mis.platzhalterkvwmapserverdomainname.conf ${USER_DIR}/networks/proxy/services/proxy/nginx/sites-available/mis.${MIS_DOMAIN_CONF}.conf
    chown 33:1700 ${USER_DIR}/networks/proxy/services/proxy/nginx/sites-available/mis.${MIS_DOMAIN_CONF}.conf
    sed -i -e "s|platzhalterkvwmapserverdomainname|mis.${MIS_DOMAIN_CONF}|g" ${USER_DIR}/networks/proxy/services/proxy/nginx/sites-available/mis.${MIS_DOMAIN_CONF}.conf
    cd ${USER_DIR}/networks/proxy/services/proxy/nginx/sites-enabled
    ln -s ../sites-available/mis.${MIS_DOMAIN_CONF}.conf
    dcm reload proxy

	echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."
}
