version: "3.6"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    image: pkorduan/postgis:13.1-3.1
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGSQL_DB=postgres
      - PGSQL_USER=postgres
      - PGSQL_PASSFILE=/root/.pgpass
      - PGSQL_MAJOR_VERSION=13.1
      - POSTGIS_VERSION=3.1
      - TERM=linux
      - COLUMNS=180
      - LINES=200
    volumes:
      - ./config/.pgpass:/root/.pgpass
      - ./config/.pgpass_gisadmin:/home/gisadmin/.pgpass
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
      - ${USER_DIR}/networks/${NETWORK_NAME}/volumes/proj/epsg:/usr/share/proj/epsg
      - ${USER_DIR}/networks/${NETWORK_NAME}/volumes/proj/MVTR2010.gsb:/usr/share/proj/MVTR2010.gsb
      - ${USER_DIR}/networks/${NETWORK_NAME}/volumes/proj/MVTRS4283.gsb:/usr/share/proj/MVTRS4283.gsb
networks:
    default:
        name: ${NETWORK_NAME}
        external: true
