version: "3.6"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}   
#    user: postgres
    image: pkorduan/postgis:13.1-3.1
    networks:
      ${NETWORK_NAME}:
        aliases:
          - ${SERVICE_NAME}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGSQL_DB=postgres
      - PGSQL_USER=postgres
      - PGSQL_PASSFILE=/root/.pgpass
      - PGSQL_MAJOR_VERSION=13.1
      - POSTGIS_VERSION=3.1
      - TERM=linux
      - COLUMNS=180
      - LINES=200
    volumes:
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}/config/.pgpass:/root/.pgpass
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}/config/.pgpass_gisadmin:/home/gisadmin/.pgpass
#      - ${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}/config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}/data:/var/lib/postgresql/data
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}/logs:/var/log/postgresql
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/proj/epsg:/usr/share/proj/epsg
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/proj/MVTR2010.gsb:/usr/share/proj/MVTR2010.gsb
      - ${USER_DIR}/networks/${NETWORK_NAME}/services/proj/MVTRS4283.gsb:/usr/share/proj/MVTRS4283.gsb
