#!/bin/bash

install_service() {

	echo "Installation von Service pgsql in Netzwerk '${NETWORK_NAME}'"
	echo "optional neuer Service-Name (Default 'pgsql'): "
	read SERVICE_NAME

	if [ -z "$SERVICE_NAME" ]; then
		SERVICE_NAME=pgsql
	fi

	echo "Service-Name=${SERVICE_NAME}"

	read -p "Passwort für User postgres:" -s POSTGRESPW
	echo "POSTGRES_PASSWORD=${POSTGRESPW}" >> ${USER_DIR}/networks/${NETWORK_NAME}/env

	SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

	if [ -d "$SERVICE_PATH" ]; then
		echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
		return 1
	fi

	mkdir ${SERVICE_PATH}
	cp -r ${USER_DIR}/kvwmap-server/service-templates/pgsql/directory_template/* ${SERVICE_PATH}
	cp    ${USER_DIR}/kvwmap-server/service-templates/pgsql/compose-template.yml ${SERVICE_PATH}/

	chown -R 999.gisadmin ${SERVICE_PATH}/
	chown root.root ${SERVICE_PATH}/config/.pgpass
	chown gisadmin.gisadmin ${SERVICE_PATH}/config/.pgpass_gisadmin
	chmod 600 ${SERVICE_PATH}/config/.pgpass*

#	read -p "Add IP to allow external access with pgAdmin Client: " PGADMIN_IP
#	echo "host    all             kvwmap          ${PGADMIN_IP}/32               md5 # externe IP for external pgAdmin access" >> ${SERVICE_PATH}/config/pg_hba.conf

	export SERVICE_NAME

	echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."
}
