version: '3'
services:
    postgres-postgis:
        build: ./build
        container_name: ${NETWORK_NAME:-kvwmap_prod}_${SERVICE_NAME:-pgsql16}
        hostname: ${NETWORK_NAME:-kvwmap_prod}_${SERVICE_NAME:-pgsql16}
        environment:
          POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
          INITDB_PGBACKREST: "true"
          INITDB_KVWMAPSP_DB: "true"
          INITDB_KVWMAP_PASSWORD: "${POSTGRES_KVWMAP_PASSWORD}"
        labels:
          monitoring.pgmonitor: true
        volumes:
        - ./data:/var/lib/postgresql/data
        - ./logs:/var/log/pgsql
        - ./pgbackrest:/pgbackrest
        - ./config/.pgpass:/var/lib/postgresql/config/.pgpass
        - ./config/postgresql.conf:/var/lib/postgresql/config/postgresql.conf
        - ./config/pg_hba.conf:/var/lib/postgresql/config/pg_hba.conf
#        - ./www:/var/www
        - ./dumps:/dumps
#        - ../../volumes/proj/proj.db:/usr/share/proj/proj.db
#        - ../../volumes/proj/epsg:/usr/share/proj/epsg
#        - ../../volumes/proj/MVTR2010.gsb:/usr/share/proj/MVTR2010.gsb
#        - ../../volumes/proj/MVTRS4283.gsb:/usr/share/proj/MVTRS4283.gs
        ports:
        - "5432:5432"
        networks:
            default:
                aliases:
                    - pgsql
networks:
    default:
        name: ${NETWORK_NAME:-kvwmap_prod}
        external: true
