#!/bin/bash

install_service() {

	echo "Installation von Service mysql in Netzwerk '${NETWORK_NAME}'"
	echo "optional neuer Service-Name (Default 'mysql'): "
	read SERVICE_NAME

	if [ -z "$SERVICE_NAME" ]; then
		SERVICE_NAME=mysql
	fi

	echo "Service-Name=${SERVICE_NAME}"

	SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

	if [ -d "$SERVICE_PATH" ]; then
		echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
		return 1
	fi

	mkdir ${SERVICE_PATH}
	cp -r ${USER_DIR}/kvwmap-server/service-templates/mysql/directory_template/* ${SERVICE_PATH}
	cp    ${USER_DIR}/kvwmap-server/service-templates/mysql/compose-template.yml ${SERVICE_PATH}/

	chown -R 999.gisadmin ${SERVICE_PATH}/

	echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."
}
